travis:
  secure:
    BINSTAR_TOKEN: FUrpqXFijPZPw2CzMdruk7rFlWa4/B1/3/YchhR6JvomH6qeGzCmRrKGSelFmc1dP2BBwUxefw1sGDDTmqm+Cvp0EBYXrA2i/GfJrJRA8q8veG+QaYS2Rct1V88bhmpmB1WC8MbTj/rCo++wPxomHEco7U8LRWUPIWdqKoxqw+JeT7MjqLleX6D7IG0Nb5rGB4bL0B2obuRRp/HT2Va1QfVBwPMEO/taRKrR2IT31CzlKYKniA3ns8lO6IQVpl1OQyBkS3LZcVR+HYVyPDjfjdaogQZnFr+Uk0rY4u3nn3jHPdTQwnkO0/ZOr2RhA0/XWsraTkx/mvy/DuFuq5mbyF/PxqxoNqILUKwUlX3UHust6zKPjUF2Q3bMejOOYNYXXVVQ+/CrTGqZ9cMCZjGNO/GzCGqeFwgLhv6tb5Vj+/Cf3sIIW6J2aqzX0jzQjpb17wOX99YibR93JHfpNYc4SJuvexvfv3OQw5uhOhTR+PVTHKoEm4FSTJldjsvDynTygYZIp7fpe46RLl1rk+4NmsLKows8T889H7od4MG9HDQr3zlrbB9SI5tebzAC/KooBNW6do3BK0H7zSO9z71aUJrRI51x6dIvxCOUFDZCvDl6kd1T3iLAXaUuzJyX/jxO8y1KD/BapHeUPPVPo6FzZSL8ObOEP7EZ920d8l6BQdw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
