travis:
  secure:
    BINSTAR_TOKEN: x8f0UGe9BhkbTCfdnnq2S1DxQyDfq9DYDPUaC/ARNqsonuMi7g9+wjA7uSFWAIZY389lJJPsqTo5EnBcYxA9bZR/Ds4aHmZRrjZKZVi9SGbkY0tWb+iUbT49pTMae149tv5zxS7YJ+qAkdYuygC22VmxVdYM8mgA6fd27wwBziS2w/ygbt4fYwkpchdSdYQ3rj+7fY2orT4f8O5Mvv41LRr8twgZsn/og2dI+NS4+dbbZiBqTXQM112kTuZCHvQOWbQ/Q2yOG3BJYiwvddFaFEzJj8fOmaiRSrpD1u3JqmS1dYsnQGlXrG8+o+CaDXIM7/1705fth4GMQBgZ2nCupeV78qoTCyT+jKb3w5avzpddeEGMTy+S+Qg1XeNhJppiS+SFhi1KwW95KL1QNxLyuuIN9yrCnhIgrxLC8Wap6pfTA5Acg9yGQVPrhf9byWCVOHjWaenbESZJq2xqasog4qUlTDOzlJ1ijbFUFZh3jw+I5MovvYvri2M8bpJOqen/yDuALb/RLq1CMWoQvt2cH9cto9NNZ9WvO2s68GoSoZv9VP7t3qt0iP5Yxg/f5tW+OJ+WzxoykYvLhYkuvkvelQVT968R+m+L9/moJqjw6xs268th90YgBfrpQyXzCcMEqfrYJGxoVDdJPnOOVmtitIBbY1semSLkrp37a4YTTME=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
